-- migrate:up
create table compras_rf (
    idcompra integer not null,
    compracod integer not null,
    codigo varchar(45) not null,
    comprafecemis date not null,
    comprafecvenc date,
    compraserie varchar(45) not null,
    compranumer varchar(45) not null,
    compradesc text not null,
    compraobs text,
    compratotalitem integer,
    compra_tipocambio decimal(20,3),
    compra_vvb decimal(20,2),
    compra_dsctoitem decimal(20,2),
    compra_og decimal(20,2),
    compra_vvitem decimal(20,2),
    compra_dsctoglobal decimal(20,2),
    compra_isc decimal(20,2),
    compra_vv decimal(20,2),
    compra_igv decimal(20,2),
    compra_pv decimal(20,2),
    compra_cargo decimal(20,2),
    compra_totv decimal(20,2),
    compra_totvmn decimal(20,2),
    compra_oa decimal(20,2),
    compra_oi decimal(20,2),
    compra_oe decimal(20,2),
    compra_cantpago integer,
    idestado integer not null,
    idproveedor integer not null,
    id_tipodocumento integer not null,
    id_tipocomprobante integer not null,
    idperiodo integer not null,
    idmoneda integer not null,
    idempresa integer not null,
    idlocal integer,
    idcentrocosto integer,
    idpersona integer,
    compra_cant_asiento integer,
    cod_us_reg integer not null,
    cod_us_act integer not null,
    fech_created_at timestamp,
    fech_updated_at timestamp,
    fech_deleted_at timestamp
    )

-- migrate:down

