"idcompra": 2,
"compracod": 2,
"codigo": "RC2",
"comprafechaemi": "2020-09-14",
"compraserie": "F029",
"compranumer": "00076117",
"compradescuent": "FARMACEUTICO",
"compratotalitem": 5,
"compratipocambio": 0.00,
"compra_vbb": 232.00,
"compra_Oper_G": 0.00,
"compra_vvitem": 232.00,
"compra_dsctoglobal": 0.00,
"compra_isc": 0.00,
"compra_vv": 232.00,
"compra_igv": 0.00,
"compra_pv": 232.00,
"compra_cargo": 0.00,
"compra_totv": 232.00,
"compra_oa": 0.00,
"compra_oi": 232.00,
"compra_oe": 0.00,
"idestado": 1,
"idproveedor": 2,
"txt_tipodocumento": 4,
"txt_tipocomprobante": 1,
"id_periodo": 202009,
"txt_moneda": 1,
"id_empresa": 1,
"id_centrocosto": 1,
"compra_cantasiento": "NULL",
"igv": 0,
"prov_ruc":,
"prov_nombre":,
"prov_direccion":,
"prov_contacto":,
"prov_telefono":,
"prov_correo": ,
"cod_us_reg": 4,
"cod_us_act": 2
(
    created_at timestamp not null,
    updated_at timestamp,
    deleted_at timestamp,
    idcompra integer not null primary key,
    compracod integer not null,
    codigo varchar(45) not null,
    compra_fecha_emi date not null,
    compra_serie varchar(45) not null,
    compra_numer varchar(45) not null,
    compra_descuent text not null,
    compra_total_item integer,
    compra_tipo_cambio decimal(20,3),
    compra_vvb decimal(20,2),
    compra_oper_g decimal(20,2),
    compra_isc decimal(20,2),
    compra_vv decimal(20,2),
    compra_igv decimal(20,2),
    compra_pv decimal(20,2),
    compra_cargo decimal(20,2),
    compra_tot_v decimal(20,2),
    compra_oper_a decimal(20,2),
    compra_oper_i decimal(20,2),
    compra_oper_e decimal(20,2),
    id_estado integer not null,
    id_proveedor integer not null,
    txt_tipodocumento varchar(15) not null,
    txt_tipocomprobante varchar(12) not null,
    id_periodo integer not null,
    txt_moneda varchar(10) not null,
    id_empresa integer not null,
    id_centro_costo integer,
    compra_cant_asiento integer,
    igv decimal(4,2) not null,
    prov_ruc varchar(11),
    prov_nombre varchar(150),
    prov_direccion varchar(15),
    prov_contacto varchar(50),
    prov_telefono varchar(20),
    prov_correo varchar(50),
    cod_usua_reg integer not null,
    cod_usua_act integer not null
    )